name = "api-verify"
main = "api-verify.js"
compatibility_date = "2024-01-01"

# Production route
routes = [
  "holistictherapydogassociation.com/api/verify",
  "www.holistictherapydogassociation.com/api/verify"
]

[[d1_databases]]
binding = "DB"
database_name = "holistic-dog-db"
database_id = "1c56ce64-c3be-4946-a644-ec7c04d4ea14"
