name = "api-logout"
main = "api-logout.js"
compatibility_date = "2024-01-01"

# Production route
routes = [
  "holistictherapydogassociation.com/api/logout",
  "www.holistictherapydogassociation.com/api/logout"
]

[[d1_databases]]
binding = "DB"
database_name = "holistic-dog-db"
database_id = "1c56ce64-c3be-4946-a644-ec7c04d4ea14"
